---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Evaluation of Water Quality in Eno River and Ellerbe Creek Between 2019 and 2020"
subtitle: "https://github.com/arl57/EDA_Final_Project_DurhamWQ"
author: "Olivia August and Analise Lindborg"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
# Load your packages
# Set your ggplot theme
# Load your datasets
```


# Rationale and Research Questions

Water quality of urban streams and rivers has been studied across the United States for the past several decades. These evaluations typically provide important insights about stressors on aquatic systems in urban environments, particularly natural pollutants such as nutrients, sediment, and heavy metals, as well as anthropogenic contaminants such as pesticides and other man-made chemicals. Many cities have programs dedicated to monitoring the health of local rivers and streams for the protection of humans and wildlife. 
  
Certain water quality parameters are commonly collected and used to assess health of urban streams. These include measurements of chemical, physical, and biological parameters that can be used independently or together to determine stream health. These parameters are often evaluated over time to highlight general trends in water quality in urban environments. In general, health of urban streams in the United States has been improving since the Clean Water Act was introduced in the 1970s.    
  
The main objective of our project was to understand current water quality trends in local urban streams between 2019 and 2020. Eno River and Ellerbe Creek in Durham, North Carolina were selected for evaluation in our study. These streams were chosen to provide a local context for evaluating recent changes in stream health. Additionally, the City of Durham collects monthly monitoring data for both Eno River and Ellerbe Creek for several metrics that they provide publicly, making this easily accessible data. This project includes an evaluation of the most common surface water quality parameters for which the City of Durham had data, including temperature, pH, dissolved oxygen, metals (zinc and copper), total phosphorus, fecal coliform, turbidity, and total suspended solids. All sites for each water body evaluated by the City of Durham were included. 
  
**Research Question:** 

1. What are the water quality trends between 2019 and 2020 for Ellerbe Creek and Eno River? 
  a. Has water quality changed between 2019 and 2020 for Ellerbe Creek and/or Eno River based on the various water quality parameters?
  b. Are there differences between sites for each stream?
  c. Have certain water quality parameters changed while others have not?
  d. Discussion point: Certain studies have shown that surface water quality improved in 2020 due to the pandemic. Do we observe the same trend?

\newpage

# Dataset Information

The data was collected from the City of Durham's water quality data web portal. The portal includes data collected by the City's Stormwater Services as part of the Water Quality Monitoring and Assessment Program. The program performs ambient stream monitoring to assess compliance with regulatory benchmarks, assess surface water impairment, identify sources for illicit discharge, and support watershed planning.  The monitoring data includes information regarding the monitoring location, conditions, weather, and measurements. Nine parameters were chosen for analysis because of their monthly measurement frequency for 2019 and 2020 at the two streams of interest. The parameters of interest include Copper, Dissolved Oxygen, Fecal Coliform, pH, Total Phosphorus, Total Suspended Solids, Temperature, Turbidity, and Zinc. To extract relevant data from the portal the stream, water quality parameters, and dates of interest were selected for the user interface and downloaded to CSV files.

Once datasets for each of the parameters were downloaded, they were read into R and compiled into a single dataframe. First, a subset of the dataframe was created to keep only relevant columns for analysis. Next, the date column to read as a date to enable plotting and time series analysis. To address duplicate measurements, measurements for the same parameter, with the same date, monitoring location, and weather were averaged. Then, the parameters measurements were pivoted to include a column for each of the nine parameters.  To map the locations of each of the monitoring stations, the water quality dataframe was joined with station coordinates. 

Water Quality Parameters | Unit | Range | Data Source
-------------------------|------|-------|-------------
Copper| ug/L | 1.1-4.135 | Durham Water Quality Web Portal
Dissolved Oxygen | mg/L | 4.7-12.1 | Durham Water Quality Web Portal
Fecal Coliform | cfu/100mL | 17.5-36000 | Durham Water Quality Web Portal
pH | Standard Units | 6.1-7.5 | Durham Water Quality Web Portal
Total Phosphorus | mg/L | 0.003 - 0.38 | Durham Water Quality Web Portal
Total Suspended Solids| mg/L | 2.5-134 | Durham Water Quality Web Portal
Temperature| C | 5.7-29.6 | Durham Water Quality Web Portal
Turbidity| NTU | 2.3-150 | Durham Water Quality Web Portal
Zinc| ug/L | 0.975-19.2 | Durham Water Quality Web Portal
Rain in the last 24 Hours | NA | Yes/No | Durham Water Quality Web Portal
Sky Condition | NA | Sunny, Partly Cloudy, Overcast | Durham Water Quality Web Portal 

\newpage

# Exploratory Analysis 
As part of the exploratory analysis, water quality data was compiled for the nine parameters for both the Eno River and Ellerbe Creek. The following sections describe the exploratory analysis completed for each waterway. 

## Eno River


## Ellerbe Creek

\newpage

# Analysis

## Zinc Yearly Comparison

## Turbidity and Recent Rainfall

## TSS and Turbidity

## Temperature and Dissolved Oxygen

## Temperature and Fecal Coliform


## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 