---
title: "Ellerbe_Analysis"
author: "Analise Lindborg"
date: "3/22/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_knit$set(root.dir = '/Users/analiselindborg/Desktop/Desktop - Analise’s MacBook Pro/Data Analytics/EDA_Final_Project_DurhamWQ')
```

## Setting up R session

```{r, message = FALSE}
getwd()
library(tidyverse)
library(lubridate)
library(sf)
library(mapview)
library(leaflet)

ellerbe.data <- read.csv("./Data/Raw/Ellerbe Creek/durham_AllData.csv")
```

## Data cleanup


```{r}
## 1. Select columns of interest
# I could not find the metadata. This may be important for the QC column (I think U in the QC column means that the value was set to the detection limit (because the value was likely below the dtection limit), but I am not sure). Also not sure what flow severity is or if we would want to use it. 
ellerbe.sub <- ellerbe.data %>%
  select(Stream.Name, Station.Name, Parameter, Date.Time, Value, QA.Code, Unit, Comments, Rain.in.Last.24.Hours, Sky.Condition)

## 2. Subsetting data for following metrics: GH, DO, pH, Fecal Coliform, Zn, Cu, TP, TSS, and turbidity
# Did not find GH info for Ellerbe Creek. Are we pulling this from USGS?
# Should we add temp? Could be interesting to see if temp has changed between the two years.
# How do we want to handle different sites for Ellerbe Creek and Eno River?

ellerbe.sub <- ellerbe.sub %>%
  filter(Parameter %in% c("Dissolved Oxygen", "pH", "Fecal Coliform", "Zinc", "Copper", "Total Phosphorus", "Total Suspended Solids", "Turbidity"))

## 3. Fix date
ellerbe.sub <- ellerbe.sub %>%
  separate(Date.Time, into = c("Date", "Time"), sep = "\\s")
ellerbe.sub$Date <- as.Date(ellerbe.sub$Date, format = "%m/%d/%y")

## 4. Some sample dates have site duplicates. Averaging these duplicate values to get one value for each parameter at each site on each data. 
ellerbe.grouped <- ellerbe.sub %>%
  group_by(Stream.Name, Station.Name, Parameter, Date, Comments, Rain.in.Last.24.Hours, Sky.Condition) %>%
 summarize(Final_Value = mean(Value)) 

## 5. Make WQ parameters their own columns for ease of comparison later on
ellerbe.all <- ellerbe.grouped %>%
  pivot_wider(names_from = Parameter, values_from = Final_Value)

## save final dataset
write.csv(ellerbe.all, "./Data/Processed/Ellerbe_processed.csv")
```

